export type VehicleCreationPayload = Record<string, unknown>;

export type VehicleCreationRecord = {
  unique_id: string;
  state_id?: string | null;
  state_name?: string | null;
  district_id?: string | null;
  district_name?: string | null;
  area_type_id?: string | null;
  area_type_name?: string | null;
  corporation_id?: string | null;
  corporation_name?: string | null;
  municipality_id?: string | null;
  municipality_name?: string | null;
  town_panchayat_id?: string | null;
  town_panchayat_name?: string | null;
  panchayat_union_id?: string | null;
  panchayat_union_name?: string | null;
  panchayat_id?: string | null;
  panchayat_name?: string | null;
  vehicle_no: string;
  vehicle_type_id?: string | null;
  fuel_type_id?: string | null;
  vehicle_type_name?: string | null;
  fuel_type_name?: string | null;
  capacity?: string | null;
  mileage_per_liter?: string | null;
  service_record?: string | null;
  vehicle_insurance?: string | null;
  insurance_expiry_date?: string | null;
  vehicle_condition?: "NEW" | "SECOND_HAND" | string | null;
  fuel_tank_capacity?: string | null;
  rc_upload?: string | null;
  vehicle_insurance_file?: string | null;
  is_active: boolean;
  company_id?: string | null;
  company_unique_id?: string | null;
  company_name?: string | null;
  project_id?: string | null;
  project_unique_id?: string | null;
  project_name?: string | null;
};
